/// Country model with emoji flag, dial code, and name.
class Country {
  const Country({
    required this.name,
    required this.dialCode,
    required this.code,
    required this.flag,
  });

  final String name;
  final String dialCode;
  final String code; // ISO 3166-1 alpha-2
  final String flag; // emoji flag

  /// Matches search query against name, dial code, or country code.
  bool matches(String query) {
    final q = query.toLowerCase().trim();
    if (q.isEmpty) return true;
    return name.toLowerCase().contains(q) ||
        dialCode.contains(q) ||
        code.toLowerCase().contains(q);
  }
}

/// Full list of countries with emoji flags and dial codes.
const List<Country> countries = [
  Country(name: 'Afghanistan', dialCode: '+93', code: 'AF', flag: '🇦🇫'),
  Country(name: 'Albania', dialCode: '+355', code: 'AL', flag: '🇦🇱'),
  Country(name: 'Algeria', dialCode: '+213', code: 'DZ', flag: '🇩🇿'),
  Country(name: 'Andorra', dialCode: '+376', code: 'AD', flag: '🇦🇩'),
  Country(name: 'Angola', dialCode: '+244', code: 'AO', flag: '🇦🇴'),
  Country(name: 'Argentina', dialCode: '+54', code: 'AR', flag: '🇦🇷'),
  Country(name: 'Armenia', dialCode: '+374', code: 'AM', flag: '🇦🇲'),
  Country(name: 'Australia', dialCode: '+61', code: 'AU', flag: '🇦🇺'),
  Country(name: 'Austria', dialCode: '+43', code: 'AT', flag: '🇦🇹'),
  Country(name: 'Azerbaijan', dialCode: '+994', code: 'AZ', flag: '🇦🇿'),
  Country(name: 'Bahamas', dialCode: '+1242', code: 'BS', flag: '🇧🇸'),
  Country(name: 'Bahrain', dialCode: '+973', code: 'BH', flag: '🇧🇭'),
  Country(name: 'Bangladesh', dialCode: '+880', code: 'BD', flag: '🇧🇩'),
  Country(name: 'Barbados', dialCode: '+1246', code: 'BB', flag: '🇧🇧'),
  Country(name: 'Belarus', dialCode: '+375', code: 'BY', flag: '🇧🇾'),
  Country(name: 'Belgium', dialCode: '+32', code: 'BE', flag: '🇧🇪'),
  Country(name: 'Belize', dialCode: '+501', code: 'BZ', flag: '🇧🇿'),
  Country(name: 'Benin', dialCode: '+229', code: 'BJ', flag: '🇧🇯'),
  Country(name: 'Bhutan', dialCode: '+975', code: 'BT', flag: '🇧🇹'),
  Country(name: 'Bolivia', dialCode: '+591', code: 'BO', flag: '🇧🇴'),
  Country(name: 'Bosnia and Herzegovina', dialCode: '+387', code: 'BA', flag: '🇧🇦'),
  Country(name: 'Botswana', dialCode: '+267', code: 'BW', flag: '🇧🇼'),
  Country(name: 'Brazil', dialCode: '+55', code: 'BR', flag: '🇧🇷'),
  Country(name: 'Brunei', dialCode: '+673', code: 'BN', flag: '🇧🇳'),
  Country(name: 'Bulgaria', dialCode: '+359', code: 'BG', flag: '🇧🇬'),
  Country(name: 'Burkina Faso', dialCode: '+226', code: 'BF', flag: '🇧🇫'),
  Country(name: 'Burundi', dialCode: '+257', code: 'BI', flag: '🇧🇮'),
  Country(name: 'Cambodia', dialCode: '+855', code: 'KH', flag: '🇰🇭'),
  Country(name: 'Cameroon', dialCode: '+237', code: 'CM', flag: '🇨🇲'),
  Country(name: 'Canada', dialCode: '+1', code: 'CA', flag: '🇨🇦'),
  Country(name: 'Chad', dialCode: '+235', code: 'TD', flag: '🇹🇩'),
  Country(name: 'Chile', dialCode: '+56', code: 'CL', flag: '🇨🇱'),
  Country(name: 'China', dialCode: '+86', code: 'CN', flag: '🇨🇳'),
  Country(name: 'Colombia', dialCode: '+57', code: 'CO', flag: '🇨🇴'),
  Country(name: 'Congo', dialCode: '+242', code: 'CG', flag: '🇨🇬'),
  Country(name: 'Costa Rica', dialCode: '+506', code: 'CR', flag: '🇨🇷'),
  Country(name: 'Croatia', dialCode: '+385', code: 'HR', flag: '🇭🇷'),
  Country(name: 'Cuba', dialCode: '+53', code: 'CU', flag: '🇨🇺'),
  Country(name: 'Cyprus', dialCode: '+357', code: 'CY', flag: '🇨🇾'),
  Country(name: 'Czech Republic', dialCode: '+420', code: 'CZ', flag: '🇨🇿'),
  Country(name: 'Denmark', dialCode: '+45', code: 'DK', flag: '🇩🇰'),
  Country(name: 'Dominican Republic', dialCode: '+1809', code: 'DO', flag: '🇩🇴'),
  Country(name: 'Ecuador', dialCode: '+593', code: 'EC', flag: '🇪🇨'),
  Country(name: 'Egypt', dialCode: '+20', code: 'EG', flag: '🇪🇬'),
  Country(name: 'El Salvador', dialCode: '+503', code: 'SV', flag: '🇸🇻'),
  Country(name: 'Estonia', dialCode: '+372', code: 'EE', flag: '🇪🇪'),
  Country(name: 'Ethiopia', dialCode: '+251', code: 'ET', flag: '🇪🇹'),
  Country(name: 'Finland', dialCode: '+358', code: 'FI', flag: '🇫🇮'),
  Country(name: 'France', dialCode: '+33', code: 'FR', flag: '🇫🇷'),
  Country(name: 'Gabon', dialCode: '+241', code: 'GA', flag: '🇬🇦'),
  Country(name: 'Georgia', dialCode: '+995', code: 'GE', flag: '🇬🇪'),
  Country(name: 'Germany', dialCode: '+49', code: 'DE', flag: '🇩🇪'),
  Country(name: 'Ghana', dialCode: '+233', code: 'GH', flag: '🇬🇭'),
  Country(name: 'Greece', dialCode: '+30', code: 'GR', flag: '🇬🇷'),
  Country(name: 'Guatemala', dialCode: '+502', code: 'GT', flag: '🇬🇹'),
  Country(name: 'Guinea', dialCode: '+224', code: 'GN', flag: '🇬🇳'),
  Country(name: 'Haiti', dialCode: '+509', code: 'HT', flag: '🇭🇹'),
  Country(name: 'Honduras', dialCode: '+504', code: 'HN', flag: '🇭🇳'),
  Country(name: 'Hong Kong', dialCode: '+852', code: 'HK', flag: '🇭🇰'),
  Country(name: 'Hungary', dialCode: '+36', code: 'HU', flag: '🇭🇺'),
  Country(name: 'Iceland', dialCode: '+354', code: 'IS', flag: '🇮🇸'),
  Country(name: 'India', dialCode: '+91', code: 'IN', flag: '🇮🇳'),
  Country(name: 'Indonesia', dialCode: '+62', code: 'ID', flag: '🇮🇩'),
  Country(name: 'Iran', dialCode: '+98', code: 'IR', flag: '🇮🇷'),
  Country(name: 'Iraq', dialCode: '+964', code: 'IQ', flag: '🇮🇶'),
  Country(name: 'Ireland', dialCode: '+353', code: 'IE', flag: '🇮🇪'),
  Country(name: 'Israel', dialCode: '+972', code: 'IL', flag: '🇮🇱'),
  Country(name: 'Italy', dialCode: '+39', code: 'IT', flag: '🇮🇹'),
  Country(name: 'Jamaica', dialCode: '+1876', code: 'JM', flag: '🇯🇲'),
  Country(name: 'Japan', dialCode: '+81', code: 'JP', flag: '🇯🇵'),
  Country(name: 'Jordan', dialCode: '+962', code: 'JO', flag: '🇯🇴'),
  Country(name: 'Kazakhstan', dialCode: '+7', code: 'KZ', flag: '🇰🇿'),
  Country(name: 'Kenya', dialCode: '+254', code: 'KE', flag: '🇰🇪'),
  Country(name: 'Kuwait', dialCode: '+965', code: 'KW', flag: '🇰🇼'),
  Country(name: 'Kyrgyzstan', dialCode: '+996', code: 'KG', flag: '🇰🇬'),
  Country(name: 'Laos', dialCode: '+856', code: 'LA', flag: '🇱🇦'),
  Country(name: 'Latvia', dialCode: '+371', code: 'LV', flag: '🇱🇻'),
  Country(name: 'Lebanon', dialCode: '+961', code: 'LB', flag: '🇱🇧'),
  Country(name: 'Libya', dialCode: '+218', code: 'LY', flag: '🇱🇾'),
  Country(name: 'Lithuania', dialCode: '+370', code: 'LT', flag: '🇱🇹'),
  Country(name: 'Luxembourg', dialCode: '+352', code: 'LU', flag: '🇱🇺'),
  Country(name: 'Macau', dialCode: '+853', code: 'MO', flag: '🇲🇴'),
  Country(name: 'Madagascar', dialCode: '+261', code: 'MG', flag: '🇲🇬'),
  Country(name: 'Malawi', dialCode: '+265', code: 'MW', flag: '🇲🇼'),
  Country(name: 'Malaysia', dialCode: '+60', code: 'MY', flag: '🇲🇾'),
  Country(name: 'Maldives', dialCode: '+960', code: 'MV', flag: '🇲🇻'),
  Country(name: 'Mali', dialCode: '+223', code: 'ML', flag: '🇲🇱'),
  Country(name: 'Malta', dialCode: '+356', code: 'MT', flag: '🇲🇹'),
  Country(name: 'Mexico', dialCode: '+52', code: 'MX', flag: '🇲🇽'),
  Country(name: 'Moldova', dialCode: '+373', code: 'MD', flag: '🇲🇩'),
  Country(name: 'Monaco', dialCode: '+377', code: 'MC', flag: '🇲🇨'),
  Country(name: 'Mongolia', dialCode: '+976', code: 'MN', flag: '🇲🇳'),
  Country(name: 'Montenegro', dialCode: '+382', code: 'ME', flag: '🇲🇪'),
  Country(name: 'Morocco', dialCode: '+212', code: 'MO', flag: '🇲🇦'),
  Country(name: 'Mozambique', dialCode: '+258', code: 'MZ', flag: '🇲🇿'),
  Country(name: 'Myanmar', dialCode: '+95', code: 'MM', flag: '🇲🇲'),
  Country(name: 'Namibia', dialCode: '+264', code: 'NA', flag: '🇳🇦'),
  Country(name: 'Nepal', dialCode: '+977', code: 'NP', flag: '🇳🇵'),
  Country(name: 'Netherlands', dialCode: '+31', code: 'NL', flag: '🇳🇱'),
  Country(name: 'New Zealand', dialCode: '+64', code: 'NZ', flag: '🇳🇿'),
  Country(name: 'Nicaragua', dialCode: '+505', code: 'NI', flag: '🇳🇮'),
  Country(name: 'Niger', dialCode: '+227', code: 'NE', flag: '🇳🇪'),
  Country(name: 'Nigeria', dialCode: '+234', code: 'NG', flag: '🇳🇬'),
  Country(name: 'North Korea', dialCode: '+850', code: 'KP', flag: '🇰🇵'),
  Country(name: 'North Macedonia', dialCode: '+389', code: 'MK', flag: '🇲🇰'),
  Country(name: 'Norway', dialCode: '+47', code: 'NO', flag: '🇳🇴'),
  Country(name: 'Oman', dialCode: '+968', code: 'OM', flag: '🇴🇲'),
  Country(name: 'Pakistan', dialCode: '+92', code: 'PK', flag: '🇵🇰'),
  Country(name: 'Palestine', dialCode: '+970', code: 'PS', flag: '🇵🇸'),
  Country(name: 'Panama', dialCode: '+507', code: 'PA', flag: '🇵🇦'),
  Country(name: 'Paraguay', dialCode: '+595', code: 'PY', flag: '🇵🇾'),
  Country(name: 'Peru', dialCode: '+51', code: 'PE', flag: '🇵🇪'),
  Country(name: 'Philippines', dialCode: '+63', code: 'PH', flag: '🇵🇭'),
  Country(name: 'Poland', dialCode: '+48', code: 'PL', flag: '🇵🇱'),
  Country(name: 'Portugal', dialCode: '+351', code: 'PT', flag: '🇵🇹'),
  Country(name: 'Qatar', dialCode: '+974', code: 'QA', flag: '🇶🇦'),
  Country(name: 'Romania', dialCode: '+40', code: 'RO', flag: '🇷🇴'),
  Country(name: 'Russia', dialCode: '+7', code: 'RU', flag: '🇷🇺'),
  Country(name: 'Rwanda', dialCode: '+250', code: 'RW', flag: '🇷🇼'),
  Country(name: 'Saudi Arabia', dialCode: '+966', code: 'SA', flag: '🇸🇦'),
  Country(name: 'Senegal', dialCode: '+221', code: 'SN', flag: '🇸🇳'),
  Country(name: 'Serbia', dialCode: '+381', code: 'RS', flag: '🇷🇸'),
  Country(name: 'Singapore', dialCode: '+65', code: 'SG', flag: '🇸🇬'),
  Country(name: 'Slovakia', dialCode: '+421', code: 'SK', flag: '🇸🇰'),
  Country(name: 'Slovenia', dialCode: '+386', code: 'SI', flag: '🇸🇮'),
  Country(name: 'Somalia', dialCode: '+252', code: 'SO', flag: '🇸🇴'),
  Country(name: 'South Africa', dialCode: '+27', code: 'ZA', flag: '🇿🇦'),
  Country(name: 'South Korea', dialCode: '+82', code: 'KR', flag: '🇰🇷'),
  Country(name: 'Spain', dialCode: '+34', code: 'ES', flag: '🇪🇸'),
  Country(name: 'Sri Lanka', dialCode: '+94', code: 'LK', flag: '🇱🇰'),
  Country(name: 'Sudan', dialCode: '+249', code: 'SD', flag: '🇸🇩'),
  Country(name: 'Sweden', dialCode: '+46', code: 'SE', flag: '🇸🇪'),
  Country(name: 'Switzerland', dialCode: '+41', code: 'CH', flag: '🇨🇭'),
  Country(name: 'Syria', dialCode: '+963', code: 'SY', flag: '🇸🇾'),
  Country(name: 'Taiwan', dialCode: '+886', code: 'TW', flag: '🇹🇼'),
  Country(name: 'Tajikistan', dialCode: '+992', code: 'TJ', flag: '🇹🇯'),
  Country(name: 'Tanzania', dialCode: '+255', code: 'TZ', flag: '🇹🇿'),
  Country(name: 'Thailand', dialCode: '+66', code: 'TH', flag: '🇹🇭'),
  Country(name: 'Togo', dialCode: '+228', code: 'TG', flag: '🇹🇬'),
  Country(name: 'Trinidad and Tobago', dialCode: '+1868', code: 'TT', flag: '🇹🇹'),
  Country(name: 'Tunisia', dialCode: '+216', code: 'TN', flag: '🇹🇳'),
  Country(name: 'Turkey', dialCode: '+90', code: 'TR', flag: '🇹🇷'),
  Country(name: 'Turkmenistan', dialCode: '+993', code: 'TM', flag: '🇹🇲'),
  Country(name: 'Uganda', dialCode: '+256', code: 'UG', flag: '🇺🇬'),
  Country(name: 'Ukraine', dialCode: '+380', code: 'UA', flag: '🇺🇦'),
  Country(name: 'United Arab Emirates', dialCode: '+971', code: 'AE', flag: '🇦🇪'),
  Country(name: 'United Kingdom', dialCode: '+44', code: 'GB', flag: '🇬🇧'),
  Country(name: 'United States', dialCode: '+1', code: 'US', flag: '🇺🇸'),
  Country(name: 'Uruguay', dialCode: '+598', code: 'UY', flag: '🇺🇾'),
  Country(name: 'Uzbekistan', dialCode: '+998', code: 'UZ', flag: '🇺🇿'),
  Country(name: 'Venezuela', dialCode: '+58', code: 'VE', flag: '🇻🇪'),
  Country(name: 'Vietnam', dialCode: '+84', code: 'VN', flag: '🇻🇳'),
  Country(name: 'Yemen', dialCode: '+967', code: 'YE', flag: '🇾🇪'),
  Country(name: 'Zambia', dialCode: '+260', code: 'ZM', flag: '🇿🇲'),
  Country(name: 'Zimbabwe', dialCode: '+263', code: 'ZW', flag: '🇿🇼'),
];

/// Find country by dial code, defaults to India.
Country findCountryByDialCode(String dialCode) {
  return countries.firstWhere(
    (c) => c.dialCode == dialCode,
    orElse: () => countries.firstWhere((c) => c.code == 'IN'),
  );
}
