// Generated by scripts/generate_launch_mark.py. Edit assets/icon/launch_mark.svg.
import 'package:flutter/material.dart';

/// Synchronous vector painting keeps the mark visible on the very first frame.
class LaunchMark extends StatelessWidget {
  const LaunchMark({required this.color, super.key});
  final Color color;

  @override
  Widget build(BuildContext context) => SizedBox.square(
    dimension: 96,
    child: CustomPaint(painter: _LaunchMarkPainter(color)),
  );
}

class _LaunchMarkPainter extends CustomPainter {
  _LaunchMarkPainter(this.color);
  final Color color;
  static final _paths = <Path>[
    Path()
      ..fillType = PathFillType.evenOdd
      ..moveTo(15, 30)
      ..lineTo(43, 14)
      ..cubicTo(47, 12, 50, 12, 54, 14)
      ..lineTo(72, 24)
      ..lineTo(60, 31)
      ..lineTo(49, 25)
      ..lineTo(25, 39)
      ..lineTo(43, 49)
      ..lineTo(33, 55)
      ..lineTo(15, 45)
      ..cubicTo(11, 43, 10, 40, 10, 37)
      ..cubicTo(10, 34, 12, 32, 15, 30)
      ..close(),
    Path()
      ..fillType = PathFillType.evenOdd
      ..moveTo(45, 41)
      ..lineTo(88, 28)
      ..cubicTo(91, 27, 93, 29, 91, 32)
      ..lineTo(75, 64)
      ..cubicTo(74, 67, 72, 67, 70, 65)
      ..lineTo(60, 53)
      ..lineTo(77, 37)
      ..lineTo(54, 49)
      ..lineTo(45, 45)
      ..cubicTo(42, 44, 42, 42, 45, 41)
      ..close(),
    Path()
      ..fillType = PathFillType.evenOdd
      ..moveTo(10, 51)
      ..lineTo(43, 70)
      ..cubicTo(47, 72, 50, 72, 54, 70)
      ..lineTo(84, 53)
      ..lineTo(91, 58)
      ..lineTo(91, 72)
      ..cubicTo(91, 75, 89, 78, 86, 80)
      ..lineTo(54, 98)
      ..cubicTo(50, 100, 46, 100, 42, 98)
      ..lineTo(15, 82)
      ..cubicTo(12, 80, 10, 77, 10, 73)
      ..close()
      ..moveTo(22, 69)
      ..lineTo(22, 74)
      ..lineTo(46, 88)
      ..cubicTo(48, 89, 50, 89, 52, 88)
      ..lineTo(79, 73)
      ..lineTo(79, 68)
      ..lineTo(54, 82)
      ..cubicTo(50, 84, 46, 84, 42, 82)
      ..close(),
  ];

  @override
  void paint(Canvas canvas, Size size) {
    canvas.save();
    canvas.scale(size.width / 100, size.height / 100);
    final paint = Paint()..color = color;
    for (final path in _paths) {
      canvas.drawPath(path, paint);
    }
    canvas.restore();
  }

  @override
  bool shouldRepaint(_LaunchMarkPainter oldDelegate) =>
      oldDelegate.color != color;
}
