"""Generate launch vectors from one SVG; no raster decoding on the first frame.

Run from the repo root: python scripts/generate_launch_mark.py
Supports the absolute M/L/C/Z commands used by this deliberately small asset.
"""
from pathlib import Path
import json
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
svg = ET.parse(ROOT / 'assets/icon/launch_mark.svg').getroot()
paths = [node.attrib['d'] for node in svg if node.tag.endswith('path')]
dart_paths = []
pdf_paths = []
for path in paths:
    tokens = re.findall(r'[MLCZ]|-?\d+(?:\.\d+)?', path)
    dart = ['Path()..fillType = PathFillType.evenOdd']
    pdf = []
    while tokens:
        command = tokens.pop(0)
        count, method, operator = {
            'M': (2, 'moveTo', 'm'), 'L': (2, 'lineTo', 'l'),
            'C': (6, 'cubicTo', 'c'), 'Z': (0, 'close', 'h'),
        }[command]
        values, tokens = tokens[:count], tokens[count:]
        dart.append(f'..{method}({", ".join(values)})')
        pdf.append(' '.join(values + [operator]))
    dart_paths.append('    ' + ''.join(dart) + ',')
    pdf_paths.append('\n'.join(pdf) + '\nf*')

(ROOT / 'lib/shared/launch_mark.dart').write_text('''// Generated by scripts/generate_launch_mark.py. Edit assets/icon/launch_mark.svg.
import 'package:flutter/material.dart';

/// Synchronous vector painting keeps the mark visible on the very first frame.
class LaunchMark extends StatelessWidget {
  const LaunchMark({required this.color, super.key});
  final Color color;

  @override
  Widget build(BuildContext context) => SizedBox.square(
    dimension: 96,
    child: CustomPaint(painter: _LaunchMarkPainter(color)),
  );
}

class _LaunchMarkPainter extends CustomPainter {
  _LaunchMarkPainter(this.color);
  final Color color;
  static final _paths = <Path>[
''' + '\n'.join(dart_paths) + '''
  ];

  @override
  void paint(Canvas canvas, Size size) {
    canvas.save();
    canvas.scale(size.width / 100, size.height / 100);
    final paint = Paint()..color = color;
    for (final path in _paths) {
      canvas.drawPath(path, paint);
    }
    canvas.restore();
  }

  @override
  bool shouldRepaint(_LaunchMarkPainter oldDelegate) => oldDelegate.color != color;
}
''')

xml_paths = '\n'.join(
    f'        <path android:fillColor="@color/splash_foreground" android:fillType="evenOdd" android:pathData="{path}" />'
    for path in paths
)
(ROOT / 'android/app/src/main/res/drawable/splash_icon.xml').write_text('''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated from assets/icon/launch_mark.svg. Vector viewport scales as a unit. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="288dp" android:height="288dp"
    android:viewportWidth="288" android:viewportHeight="288">
    <group android:translateX="96" android:translateY="96"
        android:scaleX="0.96" android:scaleY="0.96">
''' + xml_paths + '''
    </group>
</vector>
''')

# A small, resolution-independent template PDF for the iOS asset catalog.
stream = ('q\n1 0 0 -1 0 100 cm\n0 g\n' + '\n'.join(pdf_paths) + '\nQ\n').encode()
objects = [
    b'<< /Type /Catalog /Pages 2 0 R >>',
    b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 100 100] /Resources << >> /Contents 4 0 R >>',
    f'<< /Length {len(stream)} >>\nstream\n'.encode() + stream + b'endstream',
]
data = bytearray(b'%PDF-1.4\n')
offsets = [0]
for number, obj in enumerate(objects, 1):
    offsets.append(len(data))
    data.extend(f'{number} 0 obj\n'.encode() + obj + b'\nendobj\n')
xref = len(data)
data.extend(b'xref\n0 5\n0000000000 65535 f \n')
for offset in offsets[1:]:
    data.extend(f'{offset:010} 00000 n \n'.encode())
data.extend(f'trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n'.encode())
catalog = ROOT / 'ios/Runner/Assets.xcassets/LaunchImage.imageset'
(catalog / 'LaunchMark.pdf').write_bytes(data)
(catalog / 'Contents.json').write_text(json.dumps({
    'images': [{'idiom': 'universal', 'filename': 'LaunchMark.pdf'}],
    'info': {'version': 1, 'author': 'xcode'},
    'properties': {'preserves-vector-representation': True, 'template-rendering-intent': 'template'},
}, indent=2) + '\n')
